#!/bin/bash

echo "Downloading dotfiles"

declare -A DOTFILES=(
	[.zshrc]='.zshrc.remote'
	[.p10k.zsh]='.p10k.zsh'
	[.vimrc]='.vimrc'
)

for i in "${!DOTFILES[@]}"; do
	echo "Downloading $i"
	curl -o $i https://raw.githubusercontent.com/nathansmerrill/dotfiles/master/${DOTFILES[$i]}?foo=$(date +%s)
done

sed -i "s/<USERNAME>/$USER/" ~/.zshrc
